#ifndef CONFIG_H
#define CONFIG_H

#define JUMP_DURATION 400
#define MOVE_DURATION 100
#define GAME_RATE 8
#define GAME_ACCELERATION 0.003
#define MOVE_SIZE 5
#define LIFEBAR_X 50
#define LIFEBAR_Y 50
#define LIFEBAR_LENGTH 500
#define LIFEBAR_HEIGHT 50
#define HUMAN_LENGTH 100//
#define HUMAN_HEIGHT 100//
#define NORMAL_ATTACK_DURATION 1000//
#define SKILL_ATTACK_DURATION 704//
#define BIG_ATTACK_DURATION 2790//
#define DEFENCE_DURATION 2000
#define KIND_NORMAL 1
#define KIND_SKILL 2
#define KIND_BIG 3
#endif // CONFIG_H
